resources:
  repositories:
  - repository: tools
    type: git
    name: Tools

trigger: none

pool:
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds

steps:
- checkout: tools
- task: Powershell@2
  displayName: Prepare deployment
  inputs:
    targetType: inline
    script: |
      gci
      write-host "======="
      gci -recurse