apiVersion: v1
kind: Service
metadata:
  name: #{APPNAME}#
spec:
  type: #{SERVICETYPE}#
  selector:
    app: #{APPNAME}#
  ports:
    - protocol: TCP
      port: #{SERVICEPORT}#
      targetPort: #{CONTAINERPORT}#

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{APPNAME}#
spec:
  replicas: #{REPLICAS}#
  selector:
    matchLabels:
      app: #{APPNAME}# # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: #{APPNAME}# # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: #{APPNAME}#
        image: #{FULLIMAGENAME}#
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          value: "#{SPRING_DATASOURCE_PASSWORD}#"
        - name: SPRING_DATASOURCE_URL
          value: "#{SPRING_DATASOURCE_URL}#"
        - name: SPRING_DATASOURCE_USERNAME
          value: "#{SPRING_DATASOURCE_USERNAME}#"
        ports:
        - containerPort: #{CONTAINERPORT}#
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi